export const COURIER_STATUS_AVAILABLE = "AVAILABLE" as const;
export const COURIER_STATUS_UNAVAILABLE = "UNAVAILABLE" as const;
export const COURIER_STATUS_VALUES = [
  COURIER_STATUS_AVAILABLE,
  COURIER_STATUS_UNAVAILABLE,
] as const;

export const ORDER_STATUS_CREATED = "CREATED" as const;
export const ORDER_STATUS_PAID = "PAID" as const;
export const ORDER_STATUS_RESTAURANT_ACCEPTED = "RESTAURANT_ACCEPTED" as const;
export const ORDER_STATUS_RESTAURANT_REFUSED = "RESTAURANT_REFUSED" as const;
export const ORDER_STATUS_PREPARING = "PREPARING" as const;
export const ORDER_STATUS_READY_FOR_PICKUP = "READY_FOR_PICKUP" as const;
export const ORDER_STATUS_PICKED_UP = "PICKED_UP" as const;
export const ORDER_STATUS_DELIVERED = "DELIVERED" as const;

export const ORDER_STATUS_VALUES = [
  ORDER_STATUS_CREATED,
  ORDER_STATUS_PAID,
  ORDER_STATUS_RESTAURANT_ACCEPTED,
  ORDER_STATUS_RESTAURANT_REFUSED,
  ORDER_STATUS_PREPARING,
  ORDER_STATUS_READY_FOR_PICKUP,
  ORDER_STATUS_PICKED_UP,
  ORDER_STATUS_DELIVERED,
] as const;
